---
# Directory to install application (without "/" at the end)
app_dir: /home/ubuntu
# User for application (should have sudo privileges)
app_user: ubuntu

# Database vars
dbname: wize
dbuser: wize
dbpass: wize_user_pass

docker_compose_dir: /home/ubuntu/go/src/wizeblock
docker_compose_fs: /home/ubuntu/go/src/bitbucket.org/udt/wizefs

deploy_release: prod
